name: Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '2.1.202' # .NET Core 2.1 SDK 是最后一个支持 .NET Core 2.0 的 SDK

    - name: Restore dependencies
      run: dotnet restore --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --runtime win10-x64 --self-contained --no-restore --verbosity normal --output ./publish

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./publish
