name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '2.1.818' # .NET Core 2.1 SDK 是最后一个支持 .NET Core 2.0 的 SDK

    - name: Restore dependencies
      run: dotnet restore --verbosity normal

    - name: Build
      run: dotnet build --configuration Release --runtime win10-x64 --no-restore --verbosity normal

    - name: Test
      run: dotnet test --no-restore --verbosity normal
